// Mã tỉnh/thành phố theo Tổng cục Thống kê
// (63 đơn vị hành chính cấp tỉnh)
export const PROVINCES = [
  { code: "01", name: "Hà Nội" },
  { code: "79", name: "Hồ Chí Minh" },
  { code: "31", name: "Hải Phòng" },
  { code: "48", name: "Đà Nẵng" },
  { code: "92", name: "Cần Thơ" },
  { code: "75", name: "Đồng Nai" },
  { code: "74", name: "Bình Dương" },
  { code: "77", name: "Bà Rịa - Vũng Tàu" },
  { code: "56", name: "Khánh Hòa" },
  { code: "46", name: "Thừa Thiên Huế" },
  { code: "33", name: "Hưng Yên" },
  { code: "27", name: "Bắc Ninh" },
  { code: "19", name: "Thái Nguyên" },
  { code: "38", name: "Hà Tĩnh" },
  { code: "40", name: "Nghệ An" },
  { code: "26", name: "Vĩnh Phúc" },
  { code: "30", name: "Hải Dương" },
  { code: "42", name: "Quảng Bình" },
  { code: "45", name: "Quảng Trị" },
  { code: "44", name: "Quảng Ngãi" },
  { code: "50", name: "Quảng Nam" },
  { code: "52", name: "Bình Định" },
  { code: "60", name: "Bình Thuận" },
  { code: "64", name: "Gia Lai" },
  { code: "66", name: "Đắk Lắk" },
  { code: "68", name: "Lâm Đồng" },
  { code: "82", name: "Tiền Giang" },
  { code: "83", name: "Bến Tre" },
  { code: "84", name: "Trà Vinh" },
  { code: "86", name: "Vĩnh Long" },
  { code: "87", name: "Đồng Tháp" },
  { code: "89", name: "An Giang" },
  { code: "91", name: "Kiên Giang" },
  { code: "93", name: "Hậu Giang" },
  { code: "94", name: "Sóc Trăng" },
  { code: "95", name: "Bạc Liêu" },
  { code: "96", name: "Cà Mau" },
  // ... (rút gọn — danh sách đầy đủ nạp từ data trong production)
] as const;

export type ProvinceCode = (typeof PROVINCES)[number]["code"];
